[package]
name = "heimdall_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0"
log = "0.4"
env_logger = "0.9"
actix-cors = "0.6.0"